sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=keys-centos-7
  - INSTANCE=service-systemd-centos-7
  - INSTANCE=service-systemd-fedora-latest
  - INSTANCE=service-systemd-debian-8
  - INSTANCE=service-systemd-debian-9
  - INSTANCE=service-systemd-ubuntu-1604
  - INSTANCE=service-systemd-opensuse-leap
  - INSTANCE=service-upstart-ubuntu-1404
  - INSTANCE=service-sysvinit-centos-6
  - INSTANCE=service-sysvinit-amazonlinux

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
